backend/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('password_change/', authapp.password_change, name='password_change'),
    path('password_change/done/',authapp.password_change_done, name="change_password_done"),
    path('read/<int:pk>/', authapp.UserDetailView.as_view(), name='user_read'),
    path('profile/<int:pk>/', authapp.profile, name='profile'),
    path('profile_banned/<int:pk>/', authapp.profile, name='profile_banned'),
    path('profile_activate/<int:pk>/', authapp.profile, name='profile_activate'),
    path('profile_moderator_on/<int:pk>/', authapp.profile, name='profile_moderator_on'),
    path('profile_moderator_off/<int:pk>/', authapp.profile, name='profile_moderator_off'),
    path('notification_delete/<int:pk>/', authapp.delete_notification, name='notification_delete'),
]

backend/backend/urls.py
from blogapp.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls', namespace='blog')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/blogapp/urls.py
from blogapp import views as blogapp
from django.urls import path

app_name = 'blogapp'

urlpatterns = [
    path('create_post/', blogapp.PostCreateView.as_view(), name='create_post'),
    path('category', blogapp.blog, name='category'),
    path('edit_post/<int:pk>/', blogapp.edit_post, name='edit_post'),
    # path('read_post/<int:pk>/', blogapp.PostRead.as_view(), name='read_post'),
    path('read_post/<int:pk>/', blogapp.post_detail, name='read_post'),
    path('delete_post/<int:pk>/', blogapp.delete_post, name='delete_post'),
    path('comment_delete/<int:pk>/', blogapp.delete_comment, name='comment_delete'),
    path('comment_update/<int:pk>/post/<int:pkp>/', blogapp.CommentUpdateView.as_view(), name="comment_update"),
    path('comment_reply/<int:pk>/', blogapp.comment_reply, name='comment_reply'),
    path('like/<obj>/<pk>/<pkc>', blogapp.like, name='like'),
]

backend/blogapp/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone

from backend import settings


class Post(models.Model):
    CATEGORY_CHOICES = (
        ('DESING', 'Дизайн'),
        ('WEB_DEVELOPMENT', 'Веб-разработка'),
        ('MOBIL_DEVELOPMENT', 'Мобильная разработка'),
        ('MARKETING', 'Маркетинг'),
    )

    category = models.CharField(choices=CATEGORY_CHOICES, blank=False, verbose_name='Категория', max_length=150)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body_text = models.TextField()
    body_image = models.ImageField(upload_to='posts/', blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    edit_date = models.DateTimeField(default=timezone.now)
    tags = models.CharField(max_length=250, blank=False)
    is_active = models.BooleanField(default=True)
    is_like = GenericRelation('Like')

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()


class Comment(models.Model):
    post_id = models.ForeignKey('blogapp.Post', on_delete=models.CASCADE, related_name='comments')
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body_text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    parent_comment_id = models.IntegerField(default=0)
    head_comment = models.BooleanField(default=True)
    is_like = GenericRelation('Like')

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    @property
    def total_likes(self):
        return self.is_like.count()


class Like(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    liked = models.BooleanField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent_object = models.IntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)


class Notification(models.Model):
    body_text = models.TextField(verbose_name='текст сообщения')
    path = models.TextField(verbose_name='Ссылка', default=None)
    created_date = models.DateTimeField(default=timezone.now)

backend/blogapp/forms.py
from blogapp.models import Comment
from blogapp.models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

backend/blogapp/views.py
from authapp.models import BlogUser
from blogapp.forms import CommentForm, PostForm
from blogapp.models import Post, Like, Comment, Notification
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView
from django.db.models import Count


def index(request):

    posts_list = Post.objects.all().filter(is_active=True).order_by('-created_date')

    if request.method == "POST":
        # если это запрос на поиск статьи
        if request.POST.get('search_text'):
            query = request.POST.get('search_text')
            posts_search = []
            
            for post in posts_list:
                if query.lower() in post.title.lower() or query.lower() in post.body_text.lower():
                    posts_search.append(post)
            # основной список постов заменяем на поисковый
            posts_list = posts_search

        # если это запрос на фильтрацию статей
        if request.POST.get('year'):
            print('==================================')
            filter_year = request.POST.get('year')
            filter_month = request.POST.get('month')
            filter_likes = request.POST.get('likes')

            if filter_year != 'all':
                posts_list = posts_list.filter(created_date__year=filter_year)

            if filter_month != 'all':
                posts_list = posts_list.filter(created_date__month=filter_month)
            
            if filter_likes != 'all':
                print('filter_likes =', int(filter_likes))
                # фильтруем посты, где есть хотябы 1 лайк
                posts_list = posts_list.filter(is_like__liked=1)
                # суммируем лайки по каждому посту
                posts_list = posts_list.annotate(cnt_likes=Count('is_like__liked'))
                # фильтруем посты по количеству лайков в фильтре
                posts_list = posts_list.filter(cnt_likes__gte=int(filter_likes))

    # формируем список тегов
    tags_str = ''
    if posts_list:
        for post in posts_list:
            tags_str = f'{tags_str} {post.tags}'
        tags_list = list(set(tags_str.split()))[:10]
    else:
        tags_list = ''

    new_posts_list = posts_list[0:2]
    old_posts_list = posts_list[2:]
    paginator = Paginator(old_posts_list, 9)

    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'blogapp/index.html',
                  context={
                      'title': 'TipoSuperHabrBabr',
                      'posts_list': posts_list,
                      'new_posts_list': new_posts_list,
                      'old_posts_list': page_obj,
                      'tags': tags_list,
                  },
                  )


def blog(request):
    categories = {
        '0': 'ALL',
        '1': 'DESING',
        '2': 'WEB_DEVELOPMENT',
        '3': 'MOBIL_DEVELOPMENT',
        '4': 'MARKETING'
    }
    category_id = request.GET.get('id')
    current_category = categories[category_id]
    posts_list = Post.objects.filter(category=current_category, is_active=True).order_by('-created_date')
    paginator = Paginator(posts_list, 6)

    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    context = {
        'categories': categories,
        'current_category': current_category,
        'title': current_category,
        'posts_list': page_obj,
        'category_id': category_id,
    }
    return render(request, 'blogapp/blog.html', context)


def post_detail(request, pk):
    post_id = Post.objects.get(id=pk)
    tags = post_id.tags.split()
    comments = Comment.objects.filter(post_id=pk, is_active=True).order_by('-parent_comment_id')
    user_id = request.user
    new_comment = None
    model_type_posts = ContentType.objects.get_for_model(Post)
    model_type_commets = ContentType.objects.get_for_model(Comment)
    like_posts = Like.objects.filter(content_type=model_type_posts, object_id=pk, liked=True)
    like_commets = Like.objects.filter(content_type=model_type_commets, parent_object=pk, liked=True)

    path = request.build_absolute_uri()

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.save(commit=True)
            # считываем только что сохраненный комментарий
            comment = Comment.objects.get(parent_comment_id=0)
            # и записываем собственный id как родительский
            comment.parent_comment_id = comment.id
            comment.save()
            notification_to_moderator(comment.body_text, request)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        comment_form = CommentForm(initial={'user_id': user_id, 'post_id': post_id, })

    return render(request, 'blogapp/blog-post.html',
                  {'post': post_id,
                   'tags': tags,
                   'user_id': user_id,
                   'comments': comments,
                   'new_comment': new_comment,
                   'form': comment_form,
                   'like_posts': like_posts,
                   'like_commets': like_commets,
                   'path': path,
                   }
                  )


@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    model = Post
    fields = '__all__'
    template_name = 'blogapp/create_post.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        user = self.request.user
        user_id = get_object_or_404(BlogUser, username=user).id
        context_data['user'] = user
        context_data['user_id'] = user_id
        context_data['form'] = PostForm(initial={'user_id': user_id})
        return context_data

    def get_success_url(self, **kwargs):
        return reverse('index')


@login_required
def edit_post(request, pk):
    post = Post.objects.get(id=pk)

    # проверяем права юзера и статус поста
    if request.user == post.user_id or request.user.is_moderator or request.user.is_superuser and post.is_active:

        if request.method == 'POST':

            form = PostForm(request.POST, request.FILES or None, instance=post)
            if form.is_valid():
                form.save()
                post.edit_date = timezone.now()
                post.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        else:
            form = PostForm(request.POST or None, instance=post)

        content = {
            'title': 'Редактирование статьи',
            'form': form,
            'post': post,
            'user': request.user
        }
        return render(request, 'blogapp/edit_post.html', content)

    return HttpResponseForbidden('Permission Error')


@login_required
def delete_post(request, pk):
    post = Post.objects.get(id=pk)

    if request.user == post.user_id or request.user.is_moderator or request.user.is_superuser and post.is_active:
        if request.method == "POST":
            post.delete()
            return HttpResponseRedirect(reverse('index'))

        context = {
            'object': post,
            'user': request.user
        }
        return render(request, 'blogapp/post_confirm_delete.html', context)

    return HttpResponseForbidden('Permission Error')


@login_required
def delete_comment(request, pk):
    comment = Comment.objects.get(id=pk)

    if request.user == comment.user_id or request.user.is_moderator or request.user.is_superuser and comment.is_active:
        if comment.head_comment:
            # при удалении головного комментария удаляем его и все подкомментарии
            comments = Comment.objects.filter(parent_comment_id=pk)
            for comment in comments:
                comment.delete()
        else:
            # иначе удалем только один подкомментарий
            comment.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # selected_comment = get_object_or_404(Comment, id=pk)
    # selected_comment.delete()


@login_required
def comment_reply(request, pk):
    user = request.user
    comment = Comment.objects.get(id=pk)
    reply_form = CommentForm

    if request.method == "POST":
        # считываем форму
        reply_form = CommentForm(data=request.POST)

        # формируем подкомментарий
        comment_new = Comment()
        comment_new.post_id = comment.post_id
        comment_new.user_id = user
        comment_new.body_text = reply_form['body_text'].value()
        comment_new.parent_comment_id = comment.id
        comment_new.head_comment = False
        comment_new.save()
        notification_to_moderator(comment_new.body_text, request)
        # возвращаемся на страницу описания блога с комментариями
        return HttpResponseRedirect(f'/blog/read_post/{comment.post_id.id}/')

    context = {
        'comment': comment,
        'form': reply_form,
        'user': user,
    }
    return render(request, 'blogapp/comment_reply.html', context)


@method_decorator(login_required, name='dispatch')
class CommentUpdateView(UpdateView):
    model = Comment
    fields = ["body_text"]
    template_name = 'blogapp/edit_comment.html'

    def get_success_url(self, **kwargs):
        text = self.request.POST["body_text"]

backend/blogapp/templates/blogapp/includes/inc_filter.html
<div class="section" style="margin-top: -15px; margin-left:30px;">
    <div class="container">
        <div class="row">
            <!-- filter form -->
            <!-- <button class="filter-btn">Filter</button> -->

            <form action="{% url 'index' %}" method="post">
                {% csrf_token %}
                Фильтр
                <div class="filter-form">
                    <div>
                        <select size="1" name="year">
                            <option value="all">Год публикации</option>
                            <option value="2022">2022</option>
                            <option value="2021">2021</option>
                            <option value="2020">2020</option>
                            <option value="2019">2019</option>
                            <option value="2018">2018</option>
                        </select>
                    </div>

                    <div>
                        <select size="1" name="month">
                            <option value="all">Месяц публикации</option>
                            <option value="1">январь</option>
                            <option value="2">февраль</option>
                            <option value="3">март</option>
                            <option value="4">апрель</option>
                            <option value="5">май</option>
                            <option value="6">июнь</option>
                            <option value="7">июль</option>
                            <option value="8">август</option>
                            <option value="9">сентябрь</option>
                            <option value="10">октябрь</option>
                            <option value="11">ноябрь</option>
                            <option value="12">декабрь</option>
                        </select>
                    </div>

                    <div>
                        <select size="1" name="likes">
                            <option value="all">Порог лайков</option>
                            <option value="0">> 0</option>
                            <option value="1">>= 1</option>
                            <option value="2">>= 2</option>
                            <option value="5">>= 5</option>
                            <option value="10">>= 10</option>
                        </select>
                    </div>

                    <div>
                        <input type="submit" value="Применить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

backend/blogapp/templates/blogapp/includes/inc_menu.html
{% load static %}
<!-- Header -->
<header id="header">
    <!-- Nav -->
    <div id="nav">
        <!-- Main Nav -->
        <div id="nav-fixed">
            <div class="container">
                <!-- logo -->
                <div class="nav-logo">
                    <a href="{% url 'index' %}" class="logo"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
                <!-- /logo -->
                <!-- nav -->
                <ul class="nav-menu nav navbar-nav">
                    <li class="cat-1"><a href="{% url 'blog:category' %}?id=1">Дизайн</a></li>
                    <li class="cat-2"><a href="{% url 'blog:category' %}?id=2">Веб-разработка</a></li>
                    <li class="cat-3"><a href="{% url 'blog:category' %}?id=3">Мобильная разработка</a></li>
                    <li class="cat-4"><a href="{% url 'blog:category' %}?id=4">Маркетинг</a></li>
                    {% if user.is_authenticated %}
                    <li class="cat-1"><a href="{% url 'blog:create_post' %}" style="margin-left: 25px">Создать
                            статью</a></li>
                    {% endif %}
                </ul>
                <!-- /nav -->
                <!-- search & aside toggle -->
                <div class="nav-btns">
                    <button class="aside-btn"><i class="fa fa-bars"></i></button>
                    <button class="search-btn"><i class="fa fa-search"></i></button>

                    <form action="{% url 'index' %}" method="post">
                        {% csrf_token %}
                        <div class="search-form">
                            <input class="search-input" type="text" name="search_text"
                                placeholder="Enter Your Search ...">
                            <button class="search-close"><i class="fa fa-times"></i></button>
                        </div>
                    </form>

                </div>
                <!-- /search & aside toggle -->
            </div>
        </div>
        <!-- /Main Nav -->

        <!-- Aside Nav -->
        <div id="nav-aside">
            <!-- nav -->
            <div class="section-row">
                <ul class="nav-aside-menu">
                    <li><a href="{% url 'index' %}">Главная</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'blog:create_post' %}">Создать статью</a></li>
                    <li><a href="{% url 'auth:user_read' user.id %}">Личный кабинет</a> ({{ user.username }})</li>
                    <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
                    {% else %}
                    <li><a href="{% url 'auth:login' %}">Войти</a></li>
                    <li><a href="{% url 'auth:register' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
            <!-- /nav -->

            <!-- widget posts -->
            <div class="section-row">
                <h3>Свежие публикации</h3>

                {% for post in new_posts_list %}
                <div class="post post-widget">
                    <a class="post-img" href="{% url 'blog:read_post' post.id %}"><img
                            src="/media/{{ post.body_image|default:'default_images/default-post.jpg' }}" alt=""></a>
                    <div class="post-body">
                        <h3 class="post-title"><a href="blog-post.html">{{ post.title }}</a></h3>
                    </div>
                </div>
                {% endfor %}


            </div>
            <!-- /widget posts -->

            <!-- social links -->
            <div class="section-row">
                <h3>Follow us</h3>
                <ul class="nav-aside-social">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                </ul>
            </div>
            <!-- /social links -->

            <!-- aside nav close -->
            <button class="nav-aside-close"><i class="fa fa-times"></i></button>
            <!-- /aside nav close -->
        </div>
        <!-- Aside Nav -->
    </div>
    <!-- /Nav -->
</header>
<!-- /Header -->