backend/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('password_change/', authapp.password_change, name='password_change'),
    path('password_change/done/',authapp.password_change_done, name="change_password_done"),
    path('read/<int:pk>/', authapp.UserDetailView.as_view(), name='user_read'),
    path('profile/<int:pk>/', authapp.profile, name='profile'),
    path('profile_banned/<int:pk>/', authapp.profile, name='profile_banned'),
    path('profile_activate/<int:pk>/', authapp.profile, name='profile_activate'),
    path('profile_moderator_on/<int:pk>/', authapp.profile, name='profile_moderator_on'),
    path('profile_moderator_off/<int:pk>/', authapp.profile, name='profile_moderator_off'),
    path('notification_delete/<int:pk>/', authapp.delete_notification, name='notification_delete'),
]

backend/backend/urls.py
from blogapp.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls', namespace='blog')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/blogapp/urls.py
from blogapp import views as blogapp
from django.urls import path

app_name = 'blogapp'

urlpatterns = [
    path('create_post/', blogapp.PostCreateView.as_view(), name='create_post'),
    path('category', blogapp.blog, name='category'),
    path('edit_post/<int:pk>/', blogapp.edit_post, name='edit_post'),
    # path('read_post/<int:pk>/', blogapp.PostRead.as_view(), name='read_post'),
    path('read_post/<int:pk>/', blogapp.post_detail, name='read_post'),
    path('delete_post/<int:pk>/', blogapp.delete_post, name='delete_post'),
    path('comment_delete/<int:pk>/', blogapp.delete_comment, name='comment_delete'),
    path('comment_update/<int:pk>/post/<int:pkp>/', blogapp.CommentUpdateView.as_view(), name="comment_update"),
    path('comment_reply/<int:pk>/', blogapp.comment_reply, name='comment_reply'),
    path('like/<obj>/<pk>/<pkc>', blogapp.like, name='like'),
]

backend/authapp/models.py
from email.policy import default
from django.contrib.auth.models import AbstractUser
from django.db import models


class BlogUser(AbstractUser):
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    )
    avatar = models.ImageField(upload_to='users_avatars', blank=True, verbose_name='Аватар')
    age = models.PositiveSmallIntegerField(verbose_name='Возраст', default=18)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, verbose_name='Пол')
    about_me = models.TextField(verbose_name='О себе', blank=True, max_length=512)
    is_active = models.BooleanField(verbose_name='активность', default=True)
    is_moderator = models.BooleanField(verbose_name='модератор', default=False)
    is_banned = models.BooleanField(verbose_name='заблокирован', default=False)
    start_banned_time = models.DateTimeField(verbose_name='Время начала блокировки', blank=True, null=True)
    stop_banned_time = models.DateTimeField(verbose_name='Время окончания блокировки', blank=True, null=True)
    banned_time = models.IntegerField(verbose_name='Период блокировки', default=0)

backend/authapp/forms.py
from django import forms

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from authapp.models import BlogUser


class BlogUserLoginForm(AuthenticationForm):
    class Meta:
        model = BlogUser
        fields = ('username', 'password',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogUserRegisterForm(UserCreationForm):
    class Meta:
        model = BlogUser
        fields = ('username', 'email', 'first_name', 'age', 'avatar', 'about_me', 'gender', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(BlogUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogUserEditForm(UserChangeForm):
    class Meta:
        model = BlogUser
        fields = ('username', 'email', 'first_name', 'age', 'avatar', 'about_me', 'gender', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'password':
                field.widget = forms.HiddenInput()


class BannedForm(forms.Form):
    banned_time = forms.IntegerField(min_value=1, required='True')

backend/authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url, get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.views.generic import DetailView
import datetime

from authapp.forms import BlogUserLoginForm, BlogUserRegisterForm, BlogUserEditForm, BannedForm
from authapp.models import BlogUser
from blogapp.models import Notification
from blogapp.models import Post


def password_change(request,
                    template_name='authapp/change_password.html',
                    post_change_redirect=None,
                    password_change_form=PasswordChangeForm,
                    current_app=None, extra_context=None):
    if post_change_redirect is None:
        post_change_redirect = reverse('auth:change_password_done')
    else:
        post_change_redirect = resolve_url(post_change_redirect)
    if request.method == "POST":
        form = password_change_form(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            # Updating the password logs out all other sessions for the user
            # except the current one if
            # django.contrib.auth.middleware.SessionAuthenticationMiddleware
            # is enabled.
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(post_change_redirect)
    else:
        form = password_change_form(user=request.user)
    context = {
        'form': form,
        'title': 'Password change',
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)


def password_change_done(request,
                         template_name='authapp/change_password_done.html',
                         current_app=None, extra_context=None):
    context = {
        'title': 'Password change successful',
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)


def login(request):
    login_form = BlogUserLoginForm(data=request.POST)

    next = request.GET.get("returnUrl")

    if request.method == 'POST' and login_form.is_valid:
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('index'))

    content = {
        'title': 'Вход',
        'login_form': login_form,
        'next': next,
    }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    if request.method == 'POST':
        register_form = BlogUserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            user = register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))

    else:
        register_form = BlogUserRegisterForm

    content = {
        'title': 'Регистрация',
        'form': register_form,
        'path': next,
    }
    return render(request, 'authapp/register.html', content)


def edit(request):
    user = BlogUser.objects.get(pk=request.user.pk)
    if request.method == 'POST':
        edit_form = BlogUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:user_read', args=[user.pk]))
    else:
        edit_form = BlogUserEditForm(instance=request.user)

    content = {
        'title': 'Редактирование',
        'edit_form': edit_form,
        'user': user

    }
    return render(request, 'authapp/edit.html', content)


class UserDetailView(DetailView):
    model = BlogUser
    template_name = 'authapp/user_read.html'

    def get_context_data(self, **kwargs):
        ctx = super(UserDetailView, self).get_context_data(**kwargs)
        ctx['notification'] = Notification.objects.all().order_by('created_date')
        user_pk = ctx["object"].id
        user_posts = Post.objects.filter(user_id=user_pk, is_active=True).order_by('-created_date')
        ctx['posts'] = user_posts
        return ctx


def profile(request, pk):
    user = get_object_or_404(BlogUser, pk=pk)
    user_posts = Post.objects.filter(user_id=user.id, is_active=True).order_by('-created_date')
    print(f'111111111111   {user_posts}')

    if request.method == 'POST':
        # если пришла команда забанить пользователя
        if '/auth/profile_banned/' in request.path:
            banned_form = BannedForm(request.POST)
            if banned_form.is_valid():
                user.is_banned = 1
                user.banned_time = banned_form['banned_time'].value()
                user.start_banned_time = datetime.date.today()
                user.stop_banned_time = user.start_banned_time + datetime.timedelta(days=int(user.banned_time))
                user.save()
    else:
        # если простой запрос страницы
        banned_form = BannedForm()
        
        # или команда снять блокировку
        if '/auth/profile_activate/' in request.path:
            user.is_banned = 0
            user.banned_time = 0
            user.start_banned_time = None
            user.stop_banned_time = None
            user.save()
            banned_form = BannedForm()
        # команда дать модератора
        if '/auth/profile_moderator_on/' in request.path:
            user.is_moderator = True
            user.save()
        # команда убрать модератора
        if '/auth/profile_moderator_off/' in request.path:
            user.is_moderator = False
            user.save()

    content = {
        'title': 'Профиль пользователя',
        'user_read': user,
        'banned_form': banned_form,
        'posts': user_posts,
    }
    return render(request, 'authapp/profile.html', content)


def delete_notification(request, pk):
    notification = Notification.objects.get(id=pk)
    notification.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

backend/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>

    {% block css %}
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:700%7CNunito:300,600" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% endblock %}
    {% block js %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% endblock %}
</head>
<body>
{% block Header %}

{% include 'blogapp/includes/inc_menu.html' %}

<!-- /Header -->
{% endblock %}
{% block content %}

{% endblock %}
{%block footer %}
<!-- Footer -->
<footer id="footer">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-5">
                <div class="footer-widget">
                    <div class="footer-logo">
                        <a href="index.html" class="logo"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                    <ul class="footer-nav">
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Advertisement</a></li>
                    </ul>
                    <div class="footer-copyright">
								<span>&copy;
                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i
                                            class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                            href="https://colorlib.com" target="_blank">Colorlib</a>
                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-6">
                        <div class="footer-widget">
                            <h3 class="footer-title">О нас</h3>
                            <ul class="footer-links">
                                <li><a href="about.html">О нас</a></li>
                                <li><a href="#">Присоединиться</a></li>
                                <li><a href="contact.html">Контакты</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer-widget">
                            <h3 class="footer-title">Категории</h3>
                            <ul class="footer-links">
                                <li><a href="category.html">Дизайн</a></li>
                                <li><a href="category.html">Веб-разработка</a></li>
                                <li><a href="category.html">Мобильная разработка</a></li>
                                <li><a href="category.html">Маркетинг</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="footer-widget">
                    <h3 class="footer-title">Join our Newsletter</h3>
                    <div class="footer-newsletter">
                        <form>
                            <input class="input" type="email" name="newsletter" placeholder="Enter your email">
                            <button class="newsletter-btn"><i class="fa fa-paper-plane"></i></button>
                        </form>
                    </div>
                    <ul class="footer-social">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</footer>
<!-- /Footer -->
{% endblock %}
{% block plugins %}
<!-- jQuery Plugins -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}
</body>
</html>

backend/authapp/templates/authapp/change_password.html
{% extends 'authapp/base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
<div class="section">
    <!-- container -->
    <div class="container">
    <h1>Смена пароля</h1>
        <p>Для смены пароля заполните форму</p>
            <form action="." method="post">
                {{ form.as_p }}
                <p><input type="submit" value="Сменить"></p>
                {% csrf_token %}
            </form>
    </div>
</div>
{% endblock %}

backend/authapp/templates/authapp/change_password_done.html
{% extends 'authapp/base.html' %}

{% block title %}Password changed{% endblock %}

{% block content %}
<div class="section">
    <!-- container -->
    <div class="container">
        <h1>Пароль изменен</h1>
            <p>Не забудьте новый пароль!</p>
                <button class="btn btn-link form-control">
                    <a href="{% url 'auth:edit' %}">
                       Вернутся к редактированию профиля
                    </a>
                </button>
    </div>
</div>
{% endblock %}

backend/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
<div class="section">
    <!-- container -->
    <div class="container">
        <div class="row">
            <div class="box">
            <img src="/media/{{ user_read.avatar|default:'default_images/default-avatar.png' }}">
            </div>
        </div>
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Сохранить">
    </form>
    <button class="btn btn-link form-control">
        <a href="{% url 'index' %}">
           На главную
        </a>
    </button>
    <button class="btn btn-link form-control">
        <a href="{% url 'auth:password_change' %}">
            Сменить пароль
        </a>
    </button>
    <button class="btn btn-link form-control">
        <a href="{% url 'auth:login' %}">
           На страницу входа
        </a>
    </button>
    </div>
</div>
{% endblock %}

backend/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
<div class="section">
    <!-- container -->
    <div class="container">
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Войти">
    </form>
    <button class="btn btn-link form-control">
        <a href="{% url 'auth:register' %}">
            Регистрация
        </a>
    </button>
    </div>
</div>
{% endblock %}

backend/authapp/templates/authapp/profile.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<div class="section">
  <!-- container -->
  <div class="container">
    <div class="profi_item">
      <div class="profi_item_left">
        Пользователь<strong> {{ user_read.first_name|title }} -
          {{ user_read.username|title }}</strong>
        <div class="box"><img src="/media/{{ user_read.avatar|default:'default_images/default-avatar.png' }}"
            alt="{{ user_read.username }}"></div>
        <div class="post">
          <b>О себе</b>
          <p>{{ user_read.about_me }}</p>
          <b>Пол</b>
          <p>{{ user_read.gender }}</p>
          <b>Электронная почта</b>
          <p>{{ user_read.email }}</p>


          {% if user_read.id != user.id %}
          {% if user.is_moderator or user.is_superuser %}
          {% if user_read.is_banned %}
          Пользователь заблокирован на {{ user_read.banned_time }} дней. <br>
          Дата начала блокировки {{ user_read.start_banned_time }}.<br>
          Дата окончания блокировки {{ user_read.stop_banned_time }}.<br>
          <br>
          <p>
            <a href="{% url 'auth:profile_activate' user_read.id %}">
              <button>Разблокировать</button>
            </a>
          </p>
          {% else %}
          <form class="form-horizontal" action="{% url 'auth:profile_banned' user_read.id %}" method="post">
            {% csrf_token %}
            {{ banned_form.as_table }}<br>
            <input type="submit" class="" value="Заблокировать пользователя" style="margin-top: 8px;">
          </form>
          {% endif %}
          {% endif %}

          {% if not user_read.is_moderator and user.is_superuser %}
            <a href="{% url 'auth:profile_moderator_on' user_read.id %}">
              <button style="margin-top: 8px;">Сделать модератором</button>
            </a>
          {% endif %}
          {% if user_read.is_moderator and user.is_superuser %}
            <a href="{% url 'auth:profile_moderator_off' user_read.id %}">
              <button style="margin-top: 8px;">Сделать обычным пользователем</button>
            </a>
          {% endif %}
          {% endif %}
          <br>
          <p>
            <a href="{% url 'index' %}">
              <button style="margin-top: 8px;">На главную</button>
            </a>
          </p>
        </div>
      </div>
      <div class="profi_item_right">
            <b>Автор статей:</b>
            {% for post in posts %}
                <li><a href="{% url 'blogapp:read_post' post.id %}">{{ post.category }} - {{ post.title }}</a></li>
            {% endfor %}
      </div>
    </div>
    {% endblock %}

backend/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
<div class="section">
    <!-- container -->
    <div class="container">
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Регистрация">
    </form>
    <button class="btn btn-link form-control">
        <a href="{% url git branch'auth:login' %}">
           Вход
        </a>
    </button>
    </div>
</div>
{% endblock %}

backend/authapp/templates/authapp/user_read.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<div class="section">
  <!-- container -->
  <div class="container">
    <div class="profi_item">
      <div class="profi_item_left">
          Пользователь<strong>{{ object.category.first_name|title }} -
            {{ object.username|title }}</strong><br>

          {% if user.is_moderator %}
          Вы являетесь модератором. <br>
          {% endif %}
          <div class="box" style="margin-top: 30px; margin-bottom: 30px;">
            <img src="/media/{{ object.avatar|default:'default_images/default-avatar.png' }}" alt="{{ object.username }}">
          </div>
          <div class="post">
            <b>О себе</b>
            <p>{{ object.about_me }}</p>
            <b>Пол</b>
            <p>{{ object.gender }}</p>
            <b>Электронная почта</b>
            <p>{{ object.email }}</p>
            <p>
                {% if user.is_banned %}
                <h4 style="color: red">За нарушение правил
                  поведения на сайте Вы не можете оставлять комментарии
                  до {{ object.stop_banned_time }}</h4>
                {% endif %}
              <button>
                <a href={% url 'auth:edit' %}>
                  Редактировать
                </a>
              </button>
              <button>
                <a href={% url 'index' %}>
                  На главную
                </a>
              </button>
            </p>
          </div>
      </div>
      <div class="profi_item_right">
            {% if object.is_moderator %}
            <b>Вы являетесь модератором. <br></b>
            <b>Ваши уведомления:</b>
            {% for notis in notification %}
            <li><p>{{ notis.body_text }}<a href={{ notis.path }}> Перейти</a>
                    <a href="{% url 'authapp:notification_delete' notis.id %}">Удалить</a></p></li>
            {% endfor %}
            {% endif %}
            <b>Ваши статьи:</b>
            {% for post in posts %}
                <li>
                    <a href="{% url 'blogapp:read_post' post.id %}">{{ post.category }} - {{ post.title }}</a>
                    <a href="{% url 'blogapp:edit_post' post.id %}" style="margin-left:10px;"><i class="fa fa-pencil"></i></a>
                    <a href="{% url 'blogapp:delete_post' post.id %}" style="margin-left:10px;"><i class="fa fa-trash"></i></a>
                </li>
            {% endfor %}
      </div>

    </div>
  </div>
</div>
{% endblock %}