backend/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('password_change/', authapp.password_change, name='password_change'),
    path('password_change/done/',authapp.password_change_done, name="change_password_done"),
    path('read/<int:pk>/', authapp.UserDetailView.as_view(), name='user_read'),
    path('profile/<int:pk>/', authapp.profile, name='profile'),
    path('profile_banned/<int:pk>/', authapp.profile, name='profile_banned'),
    path('profile_activate/<int:pk>/', authapp.profile, name='profile_activate'),
    path('profile_moderator_on/<int:pk>/', authapp.profile, name='profile_moderator_on'),
    path('profile_moderator_off/<int:pk>/', authapp.profile, name='profile_moderator_off'),
    path('notification_delete/<int:pk>/', authapp.delete_notification, name='notification_delete'),
]

backend/backend/urls.py
from blogapp.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls', namespace='blog')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/blogapp/urls.py
from blogapp import views as blogapp
from django.urls import path

app_name = 'blogapp'

urlpatterns = [
    path('create_post/', blogapp.PostCreateView.as_view(), name='create_post'),
    path('category', blogapp.blog, name='category'),
    path('edit_post/<int:pk>/', blogapp.edit_post, name='edit_post'),
    # path('read_post/<int:pk>/', blogapp.PostRead.as_view(), name='read_post'),
    path('read_post/<int:pk>/', blogapp.post_detail, name='read_post'),
    path('delete_post/<int:pk>/', blogapp.delete_post, name='delete_post'),
    path('comment_delete/<int:pk>/', blogapp.delete_comment, name='comment_delete'),
    path('comment_update/<int:pk>/post/<int:pkp>/', blogapp.CommentUpdateView.as_view(), name="comment_update"),
    path('comment_reply/<int:pk>/', blogapp.comment_reply, name='comment_reply'),
    path('like/<obj>/<pk>/<pkc>', blogapp.like, name='like'),
]

backend/blogapp/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone

from backend import settings


class Post(models.Model):
    CATEGORY_CHOICES = (
        ('DESING', 'Дизайн'),
        ('WEB_DEVELOPMENT', 'Веб-разработка'),
        ('MOBIL_DEVELOPMENT', 'Мобильная разработка'),
        ('MARKETING', 'Маркетинг'),
    )

    category = models.CharField(choices=CATEGORY_CHOICES, blank=False, verbose_name='Категория', max_length=150)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body_text = models.TextField()
    body_image = models.ImageField(upload_to='posts/', blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    edit_date = models.DateTimeField(default=timezone.now)
    tags = models.CharField(max_length=250, blank=False)
    is_active = models.BooleanField(default=True)
    is_like = GenericRelation('Like')

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()


class Comment(models.Model):
    post_id = models.ForeignKey('blogapp.Post', on_delete=models.CASCADE, related_name='comments')
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body_text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    parent_comment_id = models.IntegerField(default=0)
    head_comment = models.BooleanField(default=True)
    is_like = GenericRelation('Like')

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    @property
    def total_likes(self):
        return self.is_like.count()


class Like(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    liked = models.BooleanField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent_object = models.IntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)


class Notification(models.Model):
    body_text = models.TextField(verbose_name='текст сообщения')
    path = models.TextField(verbose_name='Ссылка', default=None)
    created_date = models.DateTimeField(default=timezone.now)

backend/blogapp/forms.py
from blogapp.models import Comment
from blogapp.models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

backend/blogapp/views.py
from authapp.models import BlogUser
from blogapp.forms import CommentForm, PostForm
from blogapp.models import Post, Like, Comment, Notification
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView
from django.db.models import Count


def index(request):

    posts_list = Post.objects.all().filter(is_active=True).order_by('-created_date')

    if request.method == "POST":
        # если это запрос на поиск статьи
        if request.POST.get('search_text'):
            query = request.POST.get('search_text')
            posts_search = []
            
            for post in posts_list:
                if query.lower() in post.title.lower() or query.lower() in post.body_text.lower():
                    posts_search.append(post)
            # основной список постов заменяем на поисковый
            posts_list = posts_search

        # если это запрос на фильтрацию статей
        if request.POST.get('year'):
            print('==================================')
            filter_year = request.POST.get('year')
            filter_month = request.POST.get('month')
            filter_likes = request.POST.get('likes')

            if filter_year != 'all':
                posts_list = posts_list.filter(created_date__year=filter_year)

            if filter_month != 'all':
                posts_list = posts_list.filter(created_date__month=filter_month)
            
            if filter_likes != 'all':
                print('filter_likes =', int(filter_likes))
                # фильтруем посты, где есть хотябы 1 лайк
                posts_list = posts_list.filter(is_like__liked=1)
                # суммируем лайки по каждому посту
                posts_list = posts_list.annotate(cnt_likes=Count('is_like__liked'))
                # фильтруем посты по количеству лайков в фильтре
                posts_list = posts_list.filter(cnt_likes__gte=int(filter_likes))

    # формируем список тегов
    tags_str = ''
    if posts_list:
        for post in posts_list:
            tags_str = f'{tags_str} {post.tags}'
        tags_list = list(set(tags_str.split()))[:10]
    else:
        tags_list = ''

    new_posts_list = posts_list[0:2]
    old_posts_list = posts_list[2:]
    paginator = Paginator(old_posts_list, 9)

    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'blogapp/index.html',
                  context={
                      'title': 'TipoSuperHabrBabr',
                      'posts_list': posts_list,
                      'new_posts_list': new_posts_list,
                      'old_posts_list': page_obj,
                      'tags': tags_list,
                  },
                  )


def blog(request):
    categories = {
        '0': 'ALL',
        '1': 'DESING',
        '2': 'WEB_DEVELOPMENT',
        '3': 'MOBIL_DEVELOPMENT',
        '4': 'MARKETING'
    }
    category_id = request.GET.get('id')
    current_category = categories[category_id]
    posts_list = Post.objects.filter(category=current_category, is_active=True).order_by('-created_date')
    paginator = Paginator(posts_list, 6)

    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    context = {
        'categories': categories,
        'current_category': current_category,
        'title': current_category,
        'posts_list': page_obj,
        'category_id': category_id,
    }
    return render(request, 'blogapp/blog.html', context)


def post_detail(request, pk):
    post_id = Post.objects.get(id=pk)
    tags = post_id.tags.split()
    comments = Comment.objects.filter(post_id=pk, is_active=True).order_by('-parent_comment_id')
    user_id = request.user
    new_comment = None
    model_type_posts = ContentType.objects.get_for_model(Post)
    model_type_commets = ContentType.objects.get_for_model(Comment)
    like_posts = Like.objects.filter(content_type=model_type_posts, object_id=pk, liked=True)
    like_commets = Like.objects.filter(content_type=model_type_commets, parent_object=pk, liked=True)

    path = request.build_absolute_uri()

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.save(commit=True)
            # считываем только что сохраненный комментарий
            comment = Comment.objects.get(parent_comment_id=0)
            # и записываем собственный id как родительский
            comment.parent_comment_id = comment.id
            comment.save()
            notification_to_moderator(comment.body_text, request)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        comment_form = CommentForm(initial={'user_id': user_id, 'post_id': post_id, })

    return render(request, 'blogapp/blog-post.html',
                  {'post': post_id,
                   'tags': tags,
                   'user_id': user_id,
                   'comments': comments,
                   'new_comment': new_comment,
                   'form': comment_form,
                   'like_posts': like_posts,
                   'like_commets': like_commets,
                   'path': path,
                   }
                  )


@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    model = Post
    fields = '__all__'
    template_name = 'blogapp/create_post.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        user = self.request.user
        user_id = get_object_or_404(BlogUser, username=user).id
        context_data['user'] = user
        context_data['user_id'] = user_id
        context_data['form'] = PostForm(initial={'user_id': user_id})
        return context_data

    def get_success_url(self, **kwargs):
        return reverse('index')


@login_required
def edit_post(request, pk):
    post = Post.objects.get(id=pk)

    # проверяем права юзера и статус поста
    if request.user == post.user_id or request.user.is_moderator or request.user.is_superuser and post.is_active:

        if request.method == 'POST':

            form = PostForm(request.POST, request.FILES or None, instance=post)
            if form.is_valid():
                form.save()
                post.edit_date = timezone.now()
                post.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        else:
            form = PostForm(request.POST or None, instance=post)

        content = {
            'title': 'Редактирование статьи',
            'form': form,
            'post': post,
            'user': request.user
        }
        return render(request, 'blogapp/edit_post.html', content)

    return HttpResponseForbidden('Permission Error')


@login_required
def delete_post(request, pk):
    post = Post.objects.get(id=pk)

    if request.user == post.user_id or request.user.is_moderator or request.user.is_superuser and post.is_active:
        if request.method == "POST":
            post.delete()
            return HttpResponseRedirect(reverse('index'))

        context = {
            'object': post,
            'user': request.user
        }
        return render(request, 'blogapp/post_confirm_delete.html', context)

    return HttpResponseForbidden('Permission Error')


@login_required
def delete_comment(request, pk):
    comment = Comment.objects.get(id=pk)

    if request.user == comment.user_id or request.user.is_moderator or request.user.is_superuser and comment.is_active:
        if comment.head_comment:
            # при удалении головного комментария удаляем его и все подкомментарии
            comments = Comment.objects.filter(parent_comment_id=pk)
            for comment in comments:
                comment.delete()
        else:
            # иначе удалем только один подкомментарий
            comment.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # selected_comment = get_object_or_404(Comment, id=pk)
    # selected_comment.delete()


@login_required
def comment_reply(request, pk):
    user = request.user
    comment = Comment.objects.get(id=pk)
    reply_form = CommentForm

    if request.method == "POST":
        # считываем форму
        reply_form = CommentForm(data=request.POST)

        # формируем подкомментарий
        comment_new = Comment()
        comment_new.post_id = comment.post_id
        comment_new.user_id = user
        comment_new.body_text = reply_form['body_text'].value()
        comment_new.parent_comment_id = comment.id
        comment_new.head_comment = False
        comment_new.save()
        notification_to_moderator(comment_new.body_text, request)
        # возвращаемся на страницу описания блога с комментариями
        return HttpResponseRedirect(f'/blog/read_post/{comment.post_id.id}/')

    context = {
        'comment': comment,
        'form': reply_form,
        'user': user,
    }
    return render(request, 'blogapp/comment_reply.html', context)


@method_decorator(login_required, name='dispatch')
class CommentUpdateView(UpdateView):
    model = Comment
    fields = ["body_text"]
    template_name = 'blogapp/edit_comment.html'

    def get_success_url(self, **kwargs):
        text = self.request.POST["body_text"]

backend/blogapp/templates/blogapp/blog-post.html
{% extends 'blogapp/base.html' %}
{% load static %}

{% block content %}


<!-- Page Header -->
<div class="page-header" id="post-header">
    <div class="background-img" style="background-image: url('/media/{{ post.body_image|default:'default_images/default-post.jpg' }}');"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-10" style="margin-bottom: -40px">
                <div class="post-meta">
                    <a class="post-category cat-2" href="category.html">{{ post.category }}</a>
                    <span class="post-date">{{ post.created_date }}</span>
                </div>
                <h1>{{ post.title }}</h1>
            </div>
        </div>
    </div>
</div>
<!-- /Page Header -->

<!-- /Header -->

<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- Post content -->
            <div class="col-md-8">
                <div class="section-row sticky-container">
                    <div class="main-post">
                        <p>{{ post.body_text|safe|linebreaks }}</p>
<!--                        <figure class="figure-img">-->
<!--                            <img alt="" class="img-responsive" src="/media/posts/detector.png">-->
<!--                        </figure>-->
                    </div>
                    {% if user.is_authenticated %}
                        {% if post.user_id == user_id or user_id.is_superuser or user_id.is_moderator %}
                        <div class="post-shares sticky-shares">
                            <a href="{% url 'blogapp:edit_post' post.id %}"><i class="fa fa-pencil"></i></a>
                            <a href="{% url 'blogapp:delete_post' post.id %}"><i class="fa fa-trash"></i></a>
                            <a href="{% url 'blogapp:like' 'Post' post.id post.id%}"><i class="fa fa-thumbs-up"></i></a>
                            <a>{{like_posts.count}}</a>
                        </div>
                        {% else %}
                        <div class="post-shares sticky-shares">
                            <a href="{% url 'blogapp:like' 'Post' post.id post.id%}"><i class="fa fa-thumbs-up"></i></a>
                            <a>{{like_posts.count}}</a>
                        </div>
                        {% endif %}
                        {% else %}
                        <div class="post-shares sticky-shares">
                            <a><i class="fa fa-thumbs-up"></i></a>
                            <a>{{like_posts.count}}</a>
                        </div>
                    {% endif %}
                </div>
                <!-- author -->
                <div class="section-row">
                    <div class="post-author">
                        <div class="media" style="margin-left: 80px;">
                            <div class="media-body">
                                <!-- tags -->
                                <div class="aside-widget" style="margin-bottom: -15px;">
                                    <div class="tags-widget">
                                        <ul>
                                            {% for tag in tags %}
                                            <li><a href="#">#{{tag}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <!-- /tags -->
                                <div class="media-heading" style="margin-top: 32px;">
                                    <div class="media-left">
                                    <a class="post-img" href="{% url 'auth:profile' post.user_id.id %}" style="text-decoration: none;"> <img
                                        src="/media/{{ post.user_id.avatar|default:'default_images/default-avatar.png' }}" alt=""  style="height: 64px; width: 64px; object-fit: cover; border-radius: 60px;"> {{ post.user_id }}  (перейти в профиль)</a>
                                    </div>
                                </div>
                                <ul class="author-social">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /author -->
                <div class="row" style="margin-left: 70px">
                    <div class="col-md-20">
                        {% if user.is_authenticated %}
                        {% if user.is_banned %}
                        <p>За нарушения правил пользования сайтом Вы не можете
                            оставлять комментарии до {{ user.stop_banned_time }}
                        </p>
                        {% else %}


                        {% if new_comment %}
                        <h2>Your comment has been added.</h2>
                        {% endif %}

                        <h2>Оставить комментарий</h2>

                        <form action="." method="post">
                            {% csrf_token %}

                            {{ form.user_id.as_hidden }}
                            {{ form.created_date.as_hidden }}
                            {{ form.post_id.as_hidden }}
                            {{ form.is_active.as_hidden }}
                            {{ form.parent_comment_id.as_hidden }}
                            {{ form.head_comment.as_hidden }}

                            <div class="col-md-20">
                                {{ form.body_text }}
                            </div>
                            <p><input type="submit" value="Оставить"></p>
                        </form>
                        {% endif %}
                        {% else %}
                        <p>Чтобы оставить комментарий
                        <a href="{% url 'auth:login' %}?returnUrl={{path}}">войдите</a> в
                            свой аккаунт или <a href="{% url 'auth:register' %}?returnUrl={{path}}">зарегистрируйтесь.</a>
                        </p>

                        {% endif %}

                    </div>
                </div>
                <!-- comments -->
                <div class="section-row" style="margin-left: 70px">
                    <div class="section-title">
                        <h2>Комментарии: {{ comments.count }}</h2>
                    </div>

                    {% for comment in comments %}
                    <div class="post-comments">

                        <div class="media">
                            {% if comment.head_comment %}
                            <div class="media-left">
                                <img alt="" class="media-object" src="/media/{{ comment.user_id.avatar|default:'default_images/default-avatar.png' }}">
                            </div>

                            <div class="media-body">
                                <div class="media-heading">
                                    <h4>{{ comment.user_id }}</h4>

                                    <span class="time">{{ comment.created_date }}</span>
                                    {% if user.is_authenticated %}


                                    <!-- отвечать можно только на основной комментарий -->
                                    <a class="reply" href="{% url 'blogapp:comment_reply' comment.id %}">
                                        Ответить
                                    </a>

                                    {% if comment.user_id == user_id or user_id.is_superuser or user_id.is_moderator %}
                                    <a class="reply" href="{% url 'blogapp:comment_update' comment.id post.id %}">
                                        Изменить
                                    </a>
                                    <a class="reply" href="{% url 'blogapp:comment_delete' comment.id %}">
                                        Удалить
                                    </a>
                                    {% endif %}

                                    {% endif %}
                                    {% if user.is_authenticated %}


                                    <a href="{% url 'blogapp:like' 'Comment' post.id comment.id %}"
                                       style="margin: 25px; text-decoration: none;"><i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                        <span class="badge rounded-pill">

                                            <span class="visually-hidden">{{comment.total_likes}}</span>
                                          </span>
                                    </a>

                                    {% endif %}
                                </div>
                                <p1>{{ comment.body_text|safe|linebreaks }}</p1>
                            </div>
                            {% else %}
                            <div class="media-left">
                                <img alt="" class="media-object" src="/media/{{ comment.user_id.avatar|default:'default_images/default-avatar.png' }}" style="margin-left: 60px;">
                            </div>
                            <div class="media-body">
                                <div class="media-heading-reply">
                                    <h5>{{ comment.user_id }}</h5>

                                    <span class="time">{{ comment.created_date }}</span>
                                    {% if user.is_authenticated %}

                                    {% if comment.user_id == user_id or user_id.is_superuser or user_id.is_moderator %}
                                    <a class="reply" href="{% url 'blogapp:comment_delete' comment.id %}" style="color: #a7b3c6;">
                                        Удалить
                                    </a>
                                    <a class="reply" href="{% url 'blogapp:comment_update' comment.id post.id %}" style="color: #a7b3c6;">
                                        Изменить
                                    </a>
                                    {% endif %}
                                    {% endif %}

<!--                                    <a href="{% url 'blogapp:like' 'Comment' post.id comment.id %}"-->
<!--                                       style="margin: 25px">Like-->
<!--                                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">-->
<!--                                                <span class="visually-hidden">{{comment.total_likes}}</span>-->
<!--                                            </span>-->
<!--                                    </a>-->

                                    <a href="{% url 'blogapp:like' 'Comment' post.id comment.id %}"
                                       style="margin: 25px; text-decoration: none;"><i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                                <span class="visually-hidden">{{comment.total_likes}}</span>
                                            </span>
                                    </a>

                                    <p1 class="sub-comment">{{ comment.body_text|safe|linebreaks }}</p1>

                                </div>
                            </div>

                            {% endif %}

                        </div>

                        {% endfor %}
                    </div>
                </div>


            </div>
            <!-- /reply -->
        </div>

    </div>
    <!-- /container -->
</div>
<!-- /section -->

<!-- Footer -->


<!-- jQuery Plugins -->
<script src="../../static/js/jquery.min.js"></script>
<script src="../../static/js/bootstrap.min.js"></script>
<script src="../../static/js/main.js"></script>

</body>

{% endblock %}

backend/blogapp/templates/blogapp/comment_reply.html
{% extends 'blogapp/base.html' %}
{% load static %}


{% block content %}

<div class="section">
    <!-- container -->
    <div class="container">
        <form action="{% url 'blogapp:comment_reply' comment.id %}" method="post">
            {% csrf_token %}

            {{ form.user_id.as_hidden }}
            {{ form.created_date.as_hidden }}
            {{ form.post_id.as_hidden }}
            {{ form.is_active.as_hidden }}

            <div class="col-md-20">
                {{ form.body_text }}
            </div>
            <p><input type="submit" value="Add comment"></p>
        </form>
        </form>
    </div>
</div>
{% endblock %}

backend/blogapp/templates/blogapp/create_post.html
{% extends 'blogapp/base.html' %}
{% load static %}


{% block content %}
<div class="section">
    <!-- container -->
    <div class="container">
        {% if not user.is_banned %}
        <form action="" class="form-horizontal" enctype="multipart/form-data"
              method="post" style="margin: 25px;">
            {% csrf_token %}

            <div style="display: none">
                {{ form.user_id }} {{ form.created_date }}{{ form.edit_date }} {{ form.is_active }}
            </div>

            <div class="h3 text-left head">
                <p style="text-align: center">Создание статьи </p>

                <p>Пользователь {{ user }} </p>

            </div>
            Категория
            {{ form.category }}
            Заголовок
            {{ form.title }}
            Содержание
            {{ form.body_text }}
            Изображение
            {{ form.body_image }}
            Теги (через пробел)
            {{ form.tags }}


            <input class="btn btn-primary" type="submit" value="Сохранить"/>

            <a class="btn btn-danger" href="{% url 'index' %}" style="margin: 25px">Назад</a>

        </form>
        {% endif %}
        {% if user.is_banned %}
        Доступ запрещен
        {% endif %}
    </div>
</div>

{% endblock %}

backend/blogapp/templates/blogapp/edit_post.html
{% extends 'blogapp/base.html' %}
{% load static %}


{% block content %}

<div class="section">
    <!-- container -->
    <div class="container">
        {% if not user.is_banned %}
        <form action="{% url 'blogapp:edit_post' post.pk %}" class="form-horizontal" enctype="multipart/form-data"
              method="post"
              style="margin: 25px;">
            {% csrf_token %}

            <div style="display: none">
                {{ form.user_id }} {{ form.created_date }}{{ form.edit_date }} {{ form.is_active }}
            </div>

            <div class="h3 text-left head">
                <p style="text-align: center">Редактирование статьи</p>

                <p>Пользователь {{ user }} </p>

            </div>
            Категория
            {{ form.category }}
            Заголовок
            {{ form.title }}
            Содержание
            {{ form.body_text }}
            Картинка
            {{ form.body_image }}
            Тэги
            {{ form.tags }}


            <input class="btn btn-primary" type="submit"
                   value="Сохранить"/>

            <a class="btn btn-primary" href="{% url 'index' %}" style="margin: 25px">На главную</a>

            <a class="btn btn-danger" href="{% url 'blog:delete_post' post.pk %}" style="margin: 25px">Удалить</a>

        </form>
        {% endif %}
        {% if user.is_banned %}
        Доступ запрещен
        {% endif %}
    </div>
</div>
{% endblock %}